# Generated by Django 5.2 on 2025-04-08 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
